### ISSUE TITLE
I can't apply commands 

### ISSUE THREAD

**Issue by rahmanlar** [josxha/minecraft-paper-docker#2]
I use the latest image via the  default docker-compose file, when I attach to the container I can input text but it does nothing. How can I apply commands in the server?

**Comment by josxha** [comment]
It's because your input doesn't get picked up by the stdin of the server process within the container.

You can use `rcon` to access your server console but it's currently not included by default.
Please follow along:
1. Go to your data directory for your server files e.g. `cd ./data`
2. Download the latest version of `rcon-cli` from [here](https://github.com/itzg/rcon-cli/releases) with:
amd64: `wget https://github.com/itzg/rcon-cli/releases/download/1.6.0/rcon-cli_1.6.0_linux_amd64.tar.gz`
arm64: `wget https://github.com/itzg/rcon-cli/releases/download/1.6.0/rcon-cli_1.6.0_linux_arm64.tar.gz`
3. Extract **rcon-cli** with: `tar -xvzf rcon-cli_*_linux_*.tar.gz rcon-cli`
4. Remove the archive: `rm rcon-cli_*_linux_*.tar.gz`
5. Edit the **server.properties** file with `nano server.properties` and make the following changes:
`enable-rcon=true`
`rcon.password=some_password`
6. `Ctrl+o` to save and `Ctrl+x` to exit the editor.
7. Start the container (or restart it in case it is running) with `docker-compose down` and `docker-compose up -d`.
8. `docker exec -it minecraft ./rcon-cli --password some_password`
If you have changed the name of your container change "minecraft" accordingly.

Now you have access to the server console and can run commands like `op <playername>`.

To exit the console simply use `Ctrl+c`.

**Comment by rahmanlar** [comment]
Thanks, I did not know about the rcon.
